In [1]:
import numpy as np

In [2]:
def sigmoid (x):
    return 1/(1 + np.exp(-x))

In [3]:
def sigmoid_derivative(x):
    return x * (1 - x)

In [4]:
def loss(yp,y):
    return (1/2)*np.square(yp-y)
    

# Backpropagation pour un perceptron

In [5]:
X = np.array([[0.1,0.3]])
y = np.array([0.03])

In [12]:
X = np.array([0.1,0.3])
y = 0.03

# backpropagation algo (un neurone sans matrice)

In [11]:
lr=0.1
n_iters=10000
def fit(X,y):
    #W = np.array([[0.5],[0.2]])
    w1=0.5
    w2=0.2
    #bias = np.array([[1.83]])
    bias=1.83
    for _ in range(n_iters):
        print("\n----------------------------------------------------------------------iter ",_,"----------------------------------------------------------------------")
        summ = w1*X[0]+w2*X[1]+bias
        predicted_y=sigmoid(summ)
        print("Prediction = ",predicted_y)
        print("Loss = ",loss(predicted_y,y))        
        dloss_dpredicted=(predicted_y-y)
        
        dpredicted_dsum=sigmoid_derivative(predicted_y)
        #d_sum_dW=X
        dsum_dw1=X[0]
        dsum_dw2=X[1]
        A=dloss_dpredicted*dpredicted_dsum
        dloss_dw1=A*dsum_dw1
        dloss_dw2=A*dsum_dw2
        dloss_dbias=A
        
        w1=w1-dloss_dw1*lr
        w2=w2-dloss_dw2*lr
        bias=bias-dloss_dbias*lr
        print("W1 = ",w1)
        print("W2 = ",w2)
        print("Bias = ",bias)

In [12]:
X = np.array([0.1,0.3])
y = 0.03
fit(X,y)


----------------------------------------------------------------------iter  0 ----------------------------------------------------------------------
Prediction= 0.8743521434846544
Loss= 0.3564652711035652
W1 =  0.49907239074418164
W2 =  0.19721717223254484
Bias =  1.8207239074418162

----------------------------------------------------------------------iter  1 ----------------------------------------------------------------------
Prediction= 0.873226871454629
Loss= 0.35551577837158066
W1 =  0.49813892424218315
W2 =  0.1944167727265493
Bias =  1.8113892424218312

----------------------------------------------------------------------iter  2 ----------------------------------------------------------------------
Prediction= 0.8720858088973764
Loss= 0.35455425477317437
W1 =  0.4971995594106318
W2 =  0.19159867823189536
Bias =  1.8019955941063182

----------------------------------------------------------------------iter  3 -------------------------------------------------------------------

# by using matrices 1

In [15]:
lr=0.1
n_iters=2
def fit(X,y):
    W = np.array([[0.5],[0.2]])
    bias = np.array([[1.83]])
    
    for _ in range(n_iters):
        print("iter ",_,"  -----------------------")
        summ=X.dot(W)+bias
        predicted_y=sigmoid(summ)
        
        dloss_dpredicted=(predicted_y-y)
        
        dpredicted_dsum=sigmoid_derivative(predicted_y)
        
        dsum_dw=X
        
        dloss_dw=dsum_dw.T.dot(dloss_dpredicted*dpredicted_dsum)
        dloss_dbias=dloss_dpredicted*dpredicted_dsum
        
        W=W-dloss_dw*lr
        bias=bias-dloss_dbias*lr
        
        print(W)
        print(bias)


In [16]:
X = np.array([[0.1,0.3]])
y = np.array([[0.03]])
fit(X,y)

iter  0   -----------------------
[[0.49907239]
 [0.19721717]]
[[1.82072391]]
iter  1   -----------------------
[[0.49813892]
 [0.19441677]]
[[1.81138924]]


# MultiLayner Neural Network

In [25]:
inputs = np.array([[0.1,0.2]])
desired_output = np.array([[0.03]])
learning_rate= 0.1
#weights and bias initialization
hidden_weights = [[0.5,0.6],[-0.7,0.8]]
hidden_bias =[[0.4,0.9]]
output_weights = np.array([[0.35],[-0.45]])
output_bias = np.array([[0.25]])
print("-------------------------------------------------------------------")
#Learning process
#Forward Pass
hidden_layer_in = np.dot(inputs,hidden_weights) + hidden_bias
hidden_layer_out = sigmoid(hidden_layer_in)
output_layer_in = np.dot(hidden_layer_out,output_weights) + output_bias
predicted_output = sigmoid(output_layer_in)
#Backward pass
error = desired_output - predicted_output
d_predicted_output = error * sigmoid_derivative(predicted_output)
error_hidden_layer = d_predicted_output.dot(output_weights.T)
d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_out)
#Updating Weights and Biases
output_weights += hidden_layer_out.T.dot(d_predicted_output) * learning_rate
output_bias += np.sum(d_predicted_output,axis=0,keepdims=True) * learning_rate
hidden_weights += inputs.T.dot(d_hidden_layer) * learning_rate
hidden_bias += np.sum(d_hidden_layer,axis=0,keepdims=True) * learning_rate
print("updated hidden weights: ")
print(hidden_weights)
print("updated hidden biases: ")
print(hidden_bias)
print("updated output weights: ")
print(output_weights)
print("updated output biases: ")
print(output_bias)
print("Predicted out put: ",predicted_output)
loss_=loss(predicted_output,desired_output)
print("loss:",loss_)

-------------------------------------------------------------------
updated hidden weights: 
[[ 0.49989395  0.60010362]
 [-0.7002121   0.80020724]]
updated hidden biases: 
[[0.39893948 0.90103618]]
updated output weights: 
[[ 0.34283872]
 [-0.45935979]]
updated output biases: 
[[0.2375863]]
Predicted out put:  [[0.52812401]]
loss: [[0.12406377]]
