In [2]:
import numpy as np

# Test matrices

In [3]:
A=np.array([[1,2,3],[2,3,4],[3,4,5],[3,2,1],[4,3,3]])
B=np.array([[1,2,3,4],[4,3,2,1],[2,2,3,3]])
C=np.dot(A,B)

print(B.T.dot(A.T))
print("----------------------------")
print(C)



[[15 22 29 13 22]
 [14 21 28 14 23]
 [16 24 32 16 27]
 [15 23 31 17 28]]
----------------------------
[[15 14 16 15]
 [22 21 24 23]
 [29 28 32 31]
 [13 14 16 17]
 [22 23 27 28]]


In [4]:
def sigmoid (x):
    return 1/(1 + np.exp(-x))


In [5]:
def sigmoid_derivative(x):
    return x * (1 - x)

In [6]:
def loss(yp,y):
    return (1/2)*np.square(yp-y)
    

# Backpropagation pour un perceptron

In [7]:
X = np.array([[0.1,0.3]])
y = np.array([0.03])


In [12]:
X = np.array([0.1,0.3])
y = 0.03

# backpropagation algo (un neurone sans matrice)

In [27]:
lr=0.1
n_iters=10000
def fit(X,y):
    #W = np.array([[0.5],[0.2]])
    w1=0.5
    w2=0.2
    #bias = np.array([[1.83]])
    bias=1.83
    for _ in range(n_iters):
        print("iter ",_,"  -----------------------")
        summ=w1*X[0]+w2*X[1]+bias
        predicted_y=sigmoid(summ)
        print("-----------------------------------Prediction=",predicted_y)
        
        dloss_dpredicted=(predicted_y-y)
        
        dpredicted_dsum=sigmoid_derivative(predicted_y)
        #d_sum_dW=X
        dsum_dw1=X[0]
        dsum_dw2=X[1]
        A=dloss_dpredicted*dpredicted_dsum
        dloss_dw1=A*dsum_dw1
        dloss_dw2=A*dsum_dw2
        dloss_dbias=A
        
        w1=w1-dloss_dw1*lr
        w2=w2-dloss_dw2*lr
        bias=bias-dloss_dbias*lr
        
        print(w1,w2)
        print(bias)
        
        


In [28]:
X = np.array([0.1,0.3])
y = 0.03
fit(X,y)

iter  0   -----------------------
-----------------------------------Prediction= 0.8743521434846544
0.49907239074418164 0.19721717223254484
1.8207239074418162
iter  1   -----------------------
-----------------------------------Prediction= 0.873226871454629
0.49813892424218315 0.1944167727265493
1.8113892424218312
iter  2   -----------------------
-----------------------------------Prediction= 0.8720858088973764
0.4971995594106318 0.19159867823189536
1.8019955941063182
iter  3   -----------------------
-----------------------------------Prediction= 0.870928700539191
0.4962542554881416 0.1887627664644248
1.7925425548814162
iter  4   -----------------------
-----------------------------------Prediction= 0.86975528770648
0.4953029720721514 0.18590891621645417
1.7830297207215142
iter  5   -----------------------
-----------------------------------Prediction= 0.8685653083530708
0.4943456691573699 0.18303700747210952
1.7734566915736987
iter  6   -----------------------
----------------------

# by using matrices 1

In [29]:
lr=0.1
n_iters=2
def fit(X,y):
    W = np.array([[0.5],[0.2]])
    bias = np.array([[1.83]])
    
    for _ in range(n_iters):
        print("iter ",_,"  -----------------------")
        summ=X.dot(W)+bias
        predicted_y=sigmoid(summ)
        
        dloss_dpredicted=(predicted_y-y)
        
        dpredicted_dsum=sigmoid_derivative(predicted_y)
        
        dsum_dw=X
        
        dloss_dw=dsum_dw.T.dot(dloss_dpredicted*dpredicted_dsum)
        dloss_dbias=dloss_dpredicted*dpredicted_dsum
        
        W=W-dloss_dw*lr
        bias=bias-dloss_dbias*lr
        
        print(W)
        print(bias)


In [30]:
X = np.array([[0.1,0.3]])
y = np.array([[0.03]])
fit(X,y)

iter  0   -----------------------
[[0.49907239]
 [0.19721717]]
[[1.82072391]]
iter  1   -----------------------
[[0.49813892]
 [0.19441677]]
[[1.81138924]]


# MultiLayner Neural Network

In [131]:
#inputs = np.array([[0.1,0.2],[0.15,0.23]])
#desired_output = np.array([0.03,0.04])

X = np.array([[0.1,0.2]])
y = np.array([[0.03]])
learning_rate= 0.1
#weights and bias initialization
hidden_weights = [[0.5,0.6],[-0.7,0.8]]
hidden_bias =[0.4,0.9]
output_weights = np.array([[0.35],[-0.45]])
output_bias = np.array([[0.25]])
print("-------------------------------------------------------------------")
#Learning process
#Forward Pass
hidden_layer_sum = np.dot(X,hidden_weights) + hidden_bias
hidden_layer_out = sigmoid(hidden_layer_sum)
output_layer_sum = np.dot(hidden_layer_out,output_weights) + output_bias
predicted_y = sigmoid(output_layer_sum)
#Backward pass
#hidden layer
dloss_dw_h= X.T.dot((predicted_y-y)* sigmoid_derivative(predicted_y).dot(output_weights.T)*sigmoid_derivative(hidden_layer_out))
dloss_dbias_h=(predicted_y-y)* sigmoid_derivative(predicted_y).dot(output_weights.T)*sigmoid_derivative(hidden_layer_out)
#output layer
dloss_dw_out=hidden_layer_out.T.dot((predicted_y-y)*sigmoid_derivative(predicted_y))
dloss_dbias_out=(predicted_y-y)*sigmoid_derivative(predicted_y)

#update
hidden_weights-=dloss_dw_h*learning_rate
hidden_bias-=dloss_dbias_h*learning_rate
hidden_bias=np.sum(hidden_bias,axis=0,keepdims=True)

output_weights-=dloss_dw_out*learning_rate
output_bias-=np.sum(dloss_dbias_out,axis=0,keepdims=True)*learning_rate

#---------------------------------------
print("results------------------------------------")
print("updated hidden weights: ")
print(hidden_weights)
print("updated hidden biases: ")
print(hidden_bias)
print("updated output weights: ")
print(output_weights)
print("updated output biases: ")
print(output_bias)


-------------------------------------------------------------------
results------------------------------------
updated hidden weights: 
[[ 0.49989395  0.60010362]
 [-0.7002121   0.80020724]]
updated hidden biases: 
[[0.39893948 0.90103618]]
updated output weights: 
[[ 0.34283872]
 [-0.45935979]]
updated output biases: 
[[0.2375863]]
